# Generated by Django 4.2.7 on 2023-11-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_calendar", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="weeklyshifttemplatedetail",
            index=models.Index(
                fields=["day_of_week"], name="weekly_shif_day_of__a7f991_idx"
            ),
        ),
    ]
