# Generated by Django 4.2.7 on 2024-10-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_calendar", "0002_alter_weeklyshifttemplatedetail_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalweeklyshifttemplatedetail",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="historicalweeklyshifttemplatedetail",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="weeklyshifttemplatedetail",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="weeklyshifttemplatedetail",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
