# Generated by Django 4.2.7 on 2024-01-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "resource_calendar",
            "0005_alter_weeklyshifttemplatedetail_weekly_shift_template",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloperationalexceptiontype",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="historicaloperationalexceptiontype",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalweeklyshifttemplate",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="historicalweeklyshifttemplate",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="operationalexceptiontype",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="operationalexceptiontype",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="weeklyshifttemplate",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="weeklyshifttemplate",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicaloperationalexception",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="operationalexception",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
