# Generated by Django 4.2.7 on 2024-04-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "resource_calendar",
            "0007_alter_weeklyshifttemplatedetail_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalweeklyshifttemplatedetail",
            name="day_of_week",
            field=models.TextField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="weeklyshifttemplatedetail",
            name="day_of_week",
            field=models.TextField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ]
            ),
        ),
    ]
