# Generated by Django 4.2.7 on 2024-05-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "resource_calendar",
            "0008_alter_historicalweeklyshifttemplatedetail_day_of_week_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloperationalexception",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicaloperationalexceptiontype",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalweeklyshifttemplate",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalweeklyshifttemplatedetail",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="operationalexception",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="operationalexceptiontype",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="weeklyshifttemplate",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="weeklyshifttemplatedetail",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
    ]
