# Generated by Django 4.2.7 on 2024-06-26 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "resource_calendar",
            "0011_alter_historicaloperationalexception_custom_fields_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weeklyshifttemplate",
            name="weekly_shift_template_details",
        ),
        migrations.AddField(
            model_name="historicalweeklyshifttemplatedetail",
            name="weekly_shift_template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resource_calendar.weeklyshifttemplate",
            ),
        ),
        migrations.AddField(
            model_name="weeklyshifttemplatedetail",
            name="weekly_shift_template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_shift_template_details",
                to="resource_calendar.weeklyshifttemplate",
            ),
            preserve_default=False,
        ),
    ]
