version: '3.8'

services:

  db:
    image: postgres:14.2-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis-data:/var/lib/redis

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgresql-data:
    driver: local
  redis-data:
    driver: local
