# Generated by Django 4.2.7 on 2024-08-14 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resource_calendar", "0001_initial"),
        ("resource_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresource",
            name="weekly_shift_template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resource_calendar.weeklyshifttemplate",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="weekly_shift_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="resources",
                to="resource_calendar.weeklyshifttemplate",
            ),
        ),
    ]
