# Generated by Django 4.2.7 on 2023-12-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresource",
            name="external_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalresourcegroup",
            name="external_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="resource",
            name="external_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="resourcegroup",
            name="external_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
