# Generated by Django 4.2.7 on 2024-01-08 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resource_manager", "0002_historicalresource_external_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceUserRel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_user_rels",
                        to="resource_manager.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_user_rels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resource_user_rel",
                "unique_together": {("resource", "user")},
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="users",
            field=models.ManyToManyField(
                related_name="resources",
                through="resource_manager.ResourceUserRel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
