# Generated by Django 4.2.7 on 2024-01-09 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resource_manager", "0002_historicalresource_external_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="users",
            field=models.ManyToManyField(
                related_name="resources", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
