# Generated by Django 4.2.7 on 2024-01-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_manager", "0004_alter_resource_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresource",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalresourcegroup",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resourcegroup",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalresource",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalresourcegroup",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="resource",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="resourcegroup",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
