# Generated by Django 4.2.7 on 2024-03-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_manager", "0008_alter_historicalresource_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="resource_pools",
        ),
        migrations.AddField(
            model_name="resourcepool",
            name="resources",
            field=models.ManyToManyField(
                related_name="related_resources", to="resource_manager.resource"
            ),
        ),
        migrations.AlterField(
            model_name="resourcepool",
            name="work_units",
            field=models.ManyToManyField(
                related_name="related_work_units", to="resource_manager.workunit"
            ),
        ),
        migrations.AlterModelTable(
            name="historicalresourcepool",
            table="related_history",
        ),
    ]
