# Generated by Django 4.2.7 on 2024-04-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_manager", "0010_alter_resource_users_alter_resource_work_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalresource",
            name="resource_type",
            field=models.CharField(
                choices=[("Machine", "Machine"), ("Operator", "Operator")],
                default="Operator",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[("Machine", "Machine"), ("Operator", "Operator")],
                default="Operator",
                max_length=9,
            ),
        ),
    ]
