# Generated by Django 4.2.7 on 2024-05-05 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resource_manager", "0011_alter_historicalresource_resource_type_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="historicalresourcepool",
            table="resource_grp_history",
        ),
    ]
