# Generated by Django 4.2.7 on 2024-05-05 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resource_assigner", "0013_remove_assignmentconstraint_work_units"),
        ("resource_manager", "0012_alter_historicalresourcepool_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workunit",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="workunit",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="work_units",
        ),
        migrations.RemoveField(
            model_name="resourcepool",
            name="work_units",
        ),
        migrations.DeleteModel(
            name="HistoricalWorkUnit",
        ),
        migrations.DeleteModel(
            name="WorkUnit",
        ),
    ]
