# Generated by Django 4.2.7 on 2024-05-06 08:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "resource_assigner",
            "0015_rename_resource_pool_assignmentconstraint_resource_group",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resource_manager", "0013_remove_workunit_created_by_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalResourcePool",
            new_name="HistoricalResourceGroup",
        ),
        migrations.RenameModel(
            old_name="ResourcePool",
            new_name="ResourceGroup",
        ),
        migrations.AlterModelOptions(
            name="historicalresourcegroup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical resource group",
                "verbose_name_plural": "historical resource groups",
            },
        ),
    ]
