# Generated by Django 4.2.7 on 2024-05-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "resource_manager",
            "0014_rename_historicalresourcepool_historicalresourcegroup_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresource",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalresourcegroup",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="resource",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="resourcegroup",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
    ]
