# Generated by Django 4.2.7 on 2024-05-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue", "0002_remove_comment_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalissue",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="issue",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
    ]
