# Generated by Django 4.2.7 on 2024-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issue", "0004_alter_comment_custom_fields_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcomment",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalissue",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
