# Generated by Django 4.2.7 on 2024-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_created_at_user_updated_at_user_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="require_password_change",
            field=models.BooleanField(default=False),
        ),
    ]
