# Generated by Django 4.2.7 on 2024-01-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "job_manager",
            "0003_alter_dependency_external_id_alter_dependency_notes_and_more",
        ),
        ("resource_manager", "0002_historicalresource_external_id_and_more"),
        (
            "resource_calendar",
            "0005_alter_weeklyshifttemplatedetail_weekly_shift_template",
        ),
        ("operator_view", "0002_rename_item_id_historicalissue_item_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operatorviewtask",
            old_name="thumbnail",
            new_name="thumbnail_url",
        ),
        migrations.AddField(
            model_name="operatorviewtask",
            name="assigned_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="assigned_resources",
                to="resource_manager.resource",
            ),
        ),
        migrations.AddField(
            model_name="operatorviewtask",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="issues",
                to="operator_view.issue",
            ),
        ),
        migrations.CreateModel(
            name="OperatorViewException",
            fields=[
                (
                    "operationalexception_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="resource_calendar.operationalexception",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="task_item",
                        to="job_manager.task",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="task_name",
                        to="job_manager.task",
                    ),
                ),
            ],
            options={
                "db_table": "operator_view_exception",
            },
            bases=("resource_calendar.operationalexception",),
        ),
    ]
