# Generated by Django 4.2.7 on 2024-01-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_manager", "0002_historicalresource_external_id_and_more"),
        (
            "operator_view",
            "0003_rename_thumbnail_operatorviewtask_thumbnail_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatorviewtask",
            name="assigned_resource",
        ),
        migrations.AddField(
            model_name="operatorviewtask",
            name="assigned_resource",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_resources",
                to="resource_manager.resource",
            ),
        ),
    ]
