# Generated by Django 4.2.7 on 2024-01-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_assigner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assigmentrule",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
