# Generated by Django 4.2.7 on 2024-01-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resource_assigner", "0002_assigmentrule_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigmentrulecriteria",
            name="assigment_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="resource_assigner.assigmentrule",
            ),
        ),
    ]
