# Generated by Django 4.2.7 on 2024-09-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_assigner', '0003_remove_taskresourceassigment_assigment_rule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaskresourceassigment',
            name='assigment_rule',
        ),
        migrations.RemoveField(
            model_name='historicaltaskresourceassigment',
            name='resource',
        ),
    ]
