# Generated by Django 4.2.7 on 2024-01-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resource_assigner", "0003_alter_assigmentrulecriteria_assigment_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigmentrulecriteria",
            name="assigment_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="resource_assigner.assigmentrule",
            ),
        ),
        migrations.AlterField(
            model_name="taskresourceassigment",
            name="is_direct",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="taskresourceassigment",
            name="use_all_resources",
            field=models.BooleanField(default=False),
        ),
    ]
