# Generated by Django 4.2.7 on 2024-01-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resource_manager", "0005_historicalresource_notes_and_more"),
        ("resource_assigner", "0005_alter_taskresourceassigment_resources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assigmentrule",
            name="resource_group",
        ),
        migrations.RemoveField(
            model_name="taskresourceassigment",
            name="is_direct",
        ),
        migrations.RemoveField(
            model_name="taskresourceassigment",
            name="resource_count",
        ),
        migrations.RemoveField(
            model_name="taskresourceassigment",
            name="resource_group",
        ),
        migrations.RemoveField(
            model_name="taskresourceassigment",
            name="resources",
        ),
        migrations.RemoveField(
            model_name="taskresourceassigment",
            name="use_all_resources",
        ),
        migrations.AddField(
            model_name="assigmentrule",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="assigmentrule",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="taskresourceassigment",
            name="resource",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="resource_manager.resource",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="AssignmentConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("required_units", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("is_direct", models.BooleanField(default=True)),
                (
                    "assignment_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="constraints",
                        to="resource_assigner.assigmentrule",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "assignment_constraint",
            },
        ),
    ]
