# Generated by Django 4.2.7 on 2024-01-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job_manager", "0004_remove_historicaljob_note_remove_job_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resource_assigner", "0006_remove_assigmentrule_resource_group_and_more"),
        ("resource_manager", "0006_historicalresourcepool_historicalworkunit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentconstraint",
            name="resource_pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="constraints",
                to="resource_manager.resourcepool",
            ),
        ),
        migrations.AddField(
            model_name="assignmentconstraint",
            name="resources",
            field=models.ManyToManyField(
                blank=True, related_name="constraints", to="resource_manager.resource"
            ),
        ),
        migrations.AddField(
            model_name="assignmentconstraint",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="constraints",
                to="job_manager.task",
            ),
        ),
        migrations.AddField(
            model_name="assignmentconstraint",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_%(class)s_objects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignmentconstraint",
            name="work_units",
            field=models.ManyToManyField(
                blank=True, related_name="constraints", to="resource_manager.workunit"
            ),
        ),
    ]
