# Generated by Django 4.2.7 on 2024-03-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_assigner", "0007_assignmentconstraint_resource_pool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigmentrulecriteria",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="assignmentconstraint",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
