# Generated by Django 4.2.7 on 2024-03-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_manager", "0007_alter_historicalresource_resource_type_and_more"),
        ("resource_assigner", "0008_alter_assigmentrulecriteria_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentconstraint",
            name="resources",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="constraints",
                to="resource_manager.resource",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentconstraint",
            name="work_units",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="constraints",
                to="resource_manager.workunit",
            ),
        ),
    ]
