# Generated by Django 4.2.7 on 2024-03-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_manager", "0009_remove_resource_resource_pools_and_more"),
        ("resource_assigner", "0011_remove_taskresourceassigment_resource_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskresourceassigment",
            name="resource_pool",
        ),
        migrations.AddField(
            model_name="taskresourceassigment",
            name="resource_pool",
            field=models.ManyToManyField(
                blank=True, to="resource_manager.resourcepool"
            ),
        ),
    ]
