# Generated by Django 4.2.7 on 2024-05-05 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "resource_assigner",
            "0012_remove_taskresourceassigment_resource_pool_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentconstraint",
            name="work_units",
        ),
    ]
