# Generated by Django 4.2.7 on 2024-05-06 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resource_assigner", "0014_remove_assignmentconstraint_required_units"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignmentconstraint",
            old_name="resource_pool",
            new_name="resource_group",
        ),
    ]
