# Generated by Django 4.2.7 on 2024-05-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "resource_assigner",
            "0016_rename_resource_pool_taskresourceassigment_resource_group",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assigmentrule",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="assigmentrulecriteria",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="assignmentconstraint",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="taskresourceassigment",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
    ]
