# Generated by Django 4.2.7 on 2024-05-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_assigner", "0017_assigmentrule_custom_fields_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigmentrule",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="assigmentrulecriteria",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="assignmentconstraint",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="taskresourceassigment",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
