# Generated by Django 4.2.7 on 2024-05-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job_manager", "0014_alter_dependency_custom_fields_and_more"),
        ("resource_manager", "0017_alter_historicalresource_custom_fields_and_more"),
        ("resource_assigner", "0019_alter_assigmentrule_custom_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assigmentrule",
            name="resource",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="resource_manager.resource",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assigmentrule",
            name="task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="job_manager.task",
            ),
            preserve_default=False,
        ),
    ]
