# Generated by Django 4.2.7 on 2024-06-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager', '0014_alter_dependency_custom_fields_and_more'),
        ('resource_assigner', '0023_remove_assignmentconstraint_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresourceassigment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_manager.task'),
        ),
    ]
