version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    env_file:
      - ../.env

    command: sleep infinity
