# Generated by Django 4.2.7 on 2023-11-29 14:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("job_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaldependencystatus",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicaldependencystatus",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaldependencystatus",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="historicaljobstatus",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicaljobstatus",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaljobstatus",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="historicaltaskstatus",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicaltaskstatus",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaltaskstatus",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="jobstatus",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="jobstatus",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="taskstatus",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="taskstatus",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="dependency",
            name="dependency_status",
            field=models.CharField(
                choices=[
                    ("PD", "Pending"),
                    ("IP", "In Progress"),
                    ("OH", "On Hold"),
                    ("RS", "Resolved"),
                    ("CN", "Cancelled"),
                ],
                default="PD",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldependency",
            name="dependency_status",
            field=models.CharField(
                choices=[
                    ("PD", "Pending"),
                    ("IP", "In Progress"),
                    ("OH", "On Hold"),
                    ("RS", "Resolved"),
                    ("CN", "Cancelled"),
                ],
                default="PD",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="due_date",
            field=models.DateField(default=datetime.date(2023, 11, 29)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="job_status",
            field=models.CharField(
                choices=[
                    ("NP", "Not Planned"),
                    ("IP", "In Progress"),
                    ("CM", "Completed"),
                    ("CN", "Cancelled"),
                ],
                default="NP",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("NS", "Not Started"),
                    ("IP", "In Progress"),
                    ("CM", "Completed"),
                ],
                default="NS",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="job_status",
            field=models.CharField(
                choices=[
                    ("NP", "Not Planned"),
                    ("IP", "In Progress"),
                    ("CM", "Completed"),
                    ("CN", "Cancelled"),
                ],
                default="NP",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("NS", "Not Started"),
                    ("IP", "In Progress"),
                    ("CM", "Completed"),
                ],
                default="NS",
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="DependencyStatus",
        ),
        migrations.DeleteModel(
            name="HistoricalDependencyStatus",
        ),
        migrations.DeleteModel(
            name="HistoricalJobStatus",
        ),
        migrations.DeleteModel(
            name="HistoricalTaskStatus",
        ),
        migrations.DeleteModel(
            name="JobStatus",
        ),
        migrations.DeleteModel(
            name="TaskStatus",
        ),
    ]
