# Generated by Django 4.2.7 on 2023-12-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_manager", "0002_remove_historicaldependencystatus_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependency",
            name="external_id",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicaldependency",
            name="external_id",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name="historicaldependency",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="run_time_per_unit",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="setup_time",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="teardown_time",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="run_time_per_unit",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="setup_time",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="teardown_time",
            field=models.IntegerField(),
        ),
    ]
