# Generated by Django 4.2.7 on 2024-02-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_manager", "0004_remove_historicaljob_note_remove_job_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltask",
            name="run_time_per_unit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="run_time_per_unit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
