# Generated by Django 4.2.7 on 2024-03-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_manager", "0005_alter_historicaltask_run_time_per_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="duration",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="duration",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
