# Generated by Django 4.2.7 on 2024-03-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_manager", "0006_historicaltask_duration_task_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="priority",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="priority",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
