# Generated by Django 4.2.7 on 2024-04-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_manager", "0009_alter_historicaltask_item_alter_task_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="job_manager.dependency"
            ),
        ),
    ]
