# Generated by Django 4.2.7 on 2024-05-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_manager", "0011_historicalitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependency",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="dependencytype",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicaldependency",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicaldependencytype",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalitem",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicaljobtype",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicaltasktype",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalworkcenter",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="item",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="job",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="jobtype",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="task",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="tasktype",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="workcenter",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
    ]
