from django.urls import path

from .views import (
    WEEKLY_SHIFT_TEMPLATE_VIEWS,
    WEEKLY_SHIFT_TEMPLATE_DETAIL_VIEWS,
    OPERATIONAL_EXCEPTION_TYPE_VIEWS,
    OPERATIONAL_EXCEPTION_VIEWS,
)

urlpatterns = [
    # weekly shift template urls
    path(
        "weekly-shift-template/new/",
        WEEKLY_SHIFT_TEMPLATE_VIEWS.show_model_form,
        name="weekly_shift_template_form",
    ),
    path(
        "weekly-shift-template/new/<int:formset_count>",
        WEEKLY_SHIFT_TEMPLATE_VIEWS.show_model_form,
        name="weekly_shift_template_formset",
    ),
    path(
        "weekly-shift-template-create/",
        WEEKLY_SHIFT_TEMPLATE_VIEWS.create_or_update_model_instance,
        name="weekly_shift_template_create",
    ),
    path(
        "weekly-shift-templates/",
        WEEKLY_SHIFT_TEMPLATE_VIEWS.get_all_instances,
        name="weekly_shift_templates",
    ),
    path(
        "weekly-shift-template/delete/<int:id>/",
        WEEKLY_SHIFT_TEMPLATE_VIEWS.delete_obj_instance,
        name="delete_weekly_shift_template",
    ),
    path(
        "weekly-shift-template/view/<int:id>/",
        WEEKLY_SHIFT_TEMPLATE_VIEWS.show_model_form,
        name="view_weekly_shift_template",
    ),
    path(
        "weekly-shift-template/view/<int:id>/edit=<str:edit>",
        WEEKLY_SHIFT_TEMPLATE_VIEWS.show_model_form,
        name="edit_weekly_shift_template",
    ),
    path(
        "weekly-shift-template/view/<int:id>/field=<str:field>",
        WEEKLY_SHIFT_TEMPLATE_VIEWS.show_model_form,
        name="weekly_shift_template_dependencies",
    ),
    # weekly shift template detail urls
    path(
        "weekly-shift-template-detail/new/",
        WEEKLY_SHIFT_TEMPLATE_DETAIL_VIEWS.show_model_form,
        name="weekly_shift_template_detail_form",
    ),
    path(
        "weekly-shift-template-detail-create/",
        WEEKLY_SHIFT_TEMPLATE_DETAIL_VIEWS.create_or_update_model_instance,
        name="weekly_shift_template_detail_create",
    ),
    path(
        "weekly-shift-template-details/",
        WEEKLY_SHIFT_TEMPLATE_DETAIL_VIEWS.get_all_instances,
        name="weekly_shift_template_details",
    ),
    path(
        "weekly-shift-template-detail/delete/<int:id>/",
        WEEKLY_SHIFT_TEMPLATE_DETAIL_VIEWS.delete_obj_instance,
        name="delete_weekly_shift_template_detail",
    ),
    path(
        "weekly-shift-template-detail/view/<int:id>/",
        WEEKLY_SHIFT_TEMPLATE_DETAIL_VIEWS.show_model_form,
        name="view_weekly_shift_template_detail",
    ),
    path(
        "weekly-shift-template-detail/view/<int:id>/edit=<str:edit>",
        WEEKLY_SHIFT_TEMPLATE_DETAIL_VIEWS.show_model_form,
        name="edit_weekly_shift_template_detail",
    ),
    path(
        "weekly-shift-template-detail/view/<int:id>/field=<str:field>",
        WEEKLY_SHIFT_TEMPLATE_DETAIL_VIEWS.show_model_form,
        name="weekly_shift_template_detail_dependencies",
    ),
    # operational exception type urls
    path(
        "operational-exception-type/new/",
        OPERATIONAL_EXCEPTION_TYPE_VIEWS.show_model_form,
        name="operational_exception_type_form",
    ),
    path(
        "operational-exception-type-create/",
        OPERATIONAL_EXCEPTION_TYPE_VIEWS.create_or_update_model_instance,
        name="operational_exception_type_create",
    ),
    path(
        "operational-exception-types/",
        OPERATIONAL_EXCEPTION_TYPE_VIEWS.get_all_instances,
        name="operational_exception_types",
    ),
    path(
        "operational-exception-type/delete/<int:id>/",
        OPERATIONAL_EXCEPTION_TYPE_VIEWS.delete_obj_instance,
        name="delete_operational_exception_type",
    ),
    path(
        "operational-exception-type/view/<int:id>/",
        OPERATIONAL_EXCEPTION_TYPE_VIEWS.show_model_form,
        name="view_operational_exception_type",
    ),
    path(
        "operational-exception-type/view/<int:id>/edit=<str:edit>",
        OPERATIONAL_EXCEPTION_TYPE_VIEWS.show_model_form,
        name="edit_operational_exception_type",
    ),
    path(
        "operational-exception-type/view/<int:id>/field=<str:field>",
        OPERATIONAL_EXCEPTION_TYPE_VIEWS.show_model_form,
        name="operational_exception_type_dependencies",
    ),
    # operational exception urls
    path(
        "operational-exception/new/",
        OPERATIONAL_EXCEPTION_VIEWS.show_model_form,
        name="operational_exception_form",
    ),
    path(
        "operational-exception-create/",
        OPERATIONAL_EXCEPTION_VIEWS.create_or_update_model_instance,
        name="operational_exception_create",
    ),
    path(
        "operational-exceptions/",
        OPERATIONAL_EXCEPTION_VIEWS.get_all_instances,
        name="operational_exceptions",
    ),
    path(
        "operational-exception/delete/<int:id>/",
        OPERATIONAL_EXCEPTION_VIEWS.delete_obj_instance,
        name="delete_operational_exception",
    ),
    path(
        "operational-exception/view/<int:id>/",
        OPERATIONAL_EXCEPTION_VIEWS.show_model_form,
        name="view_operational_exception",
    ),
    path(
        "operational-exception/view/<int:id>/edit=<str:edit>",
        OPERATIONAL_EXCEPTION_VIEWS.show_model_form,
        name="edit_operational_exception",
    ),
    path(
        "operational-exception/view/<int:id>/field=<str:field>",
        OPERATIONAL_EXCEPTION_VIEWS.show_model_form,
        name="operational_exception_dependencies",
    ),
]
