# Generated by Django 4.2.7 on 2024-03-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceallocations",
            name="run_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="scheduler.schedulerruns",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourceintervals",
            name="run_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="scheduler.schedulerruns",
            ),
            preserve_default=False,
        ),
    ]
