# Generated by Django 4.2.7 on 2024-03-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0002_resourceallocations_run_id_resourceintervals_run_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceintervals",
            name="interval_end",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="resourceintervals",
            name="interval_start",
            field=models.TimeField(),
        ),
    ]
