# Generated by Django 4.2.7 on 2024-03-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_alter_resourceintervals_interval_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceintervals",
            name="interval_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="resourceintervals",
            name="interval_start",
            field=models.DateTimeField(),
        ),
    ]
