# Generated by Django 4.2.7 on 2024-05-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "scheduler",
            "0005_historicalschedulerruns_historicalresourceintervals_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresourceallocations",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalresourceintervals",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalschedulerruns",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="resourceallocations",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="resourceintervals",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="schedulerruns",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
    ]
