# Generated by Django 4.2.7 on 2024-05-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0006_historicalresourceallocations_custom_fields_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalresourceallocations",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalresourceintervals",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalschedulerruns",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="resourceallocations",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="resourceintervals",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="schedulerruns",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
