# Generated by Django 4.2.7 on 2024-05-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_customfield_field_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfield",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalcustomfield",
            name="custom_fields",
            field=models.JSONField(default=dict),
        ),
    ]
