# Generated by Django 4.2.7 on 2024-05-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_customfield_custom_fields_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfield",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="customfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "number"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("datetime", "Datetime"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomfield",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalcustomfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "number"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("datetime", "Datetime"),
                ],
                max_length=10,
            ),
        ),
    ]
