name: Models CI

on:
  pull_request:
    branches:
      - main
      - development
      - staging
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Create virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run migrations (check for migration issues)
        run: |
          source venv/bin/activate
          python src/manage.py migrate
        env:
          DJANGO_ENV: development
          DATABASE: sqlite3

      - name: Start the backend (checks if the server starts)
        run: |
          source venv/bin/activate 
          python src/manage.py runserver &
          sleep 10

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest src/ -W ignore
        env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
